package com.manuelpedreira.shorturl.services;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.manuelpedreira.shorturl.repositories.UrlRepository;

@Service
public class ShortCodeGeneratorService {

  @Autowired
  private UrlRepository urlRepository;

  private static final Logger logger = LoggerFactory.getLogger(ShortCodeGeneratorService.class);

  public String generarShortCode() {

    String newShortCode = java.util.UUID.randomUUID().toString().replaceAll("[^a-zA-Z0-9]", "").substring(0, 7);

    if (urlRepository.existsByShortCode(newShortCode)) {
      logger.warn("Collision generated by ShortUrl: " + newShortCode);
      newShortCode = generarShortCode();
    }
    return newShortCode;
  }
}
